cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myProject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include(('myApp.urls','myApp'), namespace='myApp')),
    re_path(r'^provider/', include(('serviceProviderApp.urls','serviceProviderApp'), namespace='serviceProviderApp')),
    re_path(r'^user/', include(('userModule.urls','userModule'), namespace='userModule')),
    re_path(r'^cart/', include(('cart.urls','cart'), namespace='cart')),
    re_path(r'^orders/', include(('orders.urls','orders'), namespace='orders')),
    url(r'^payment/', include(('payment.urls','payment'), namespace='payment')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

serviceProviderApp/urls.py
from django.urls import path, re_path
from . import views
from serviceProviderApp.views import KitchenUpdate, ProviderRegisterView,registerKitchen
from userModule.views import createMenuItem,createKitchen
from django.conf.urls import url

urlpatterns = [
    re_path(r'^$',views.ProviderRegisterView, name='providersignup'),
    #re_path(r'^$',registerKitchen.as_view(), name='providersignup'),
    re_path(r'^create/$',createKitchen.as_view(),name='kitchenCreate'),
    re_path(r'^(?P<pk>\d+)$',KitchenUpdate.as_view(),name='kitchenUpdate'),
    #url(r'^(?P<pk>\d+)/createMenuItem$', createMenuItem.as_view(), name='createMenuItem'),
    url(r'^createMenuItem$', createMenuItem.as_view(), name='createMenuItem'),
    #url(r'^$', views.product_list, name='product_list'),
    #url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    #url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

userModule/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse
from userModule.views import updateMenuItem,deleteMenuItem,updateRegisteredKitchen,deleteRegisteredKitchen

urlpatterns = [
    re_path(r'^$', views.kitchen_list, name='kitchen_list'),
    re_path(r'^(?P<id>\d+)/$', views.kitchen_detail, name='kitchen_detail'),
    re_path(r'^(?P<pk>\d+)/editMenuItem$', updateMenuItem.as_view(), name='editMenuItem'),
    re_path(r'^(?P<pk>\d+)/deleteMenuItem$', deleteMenuItem.as_view(), name='deleteMenuItem'),
    re_path(r'^(?P<pk>\d+)/editKitchen$', updateRegisteredKitchen.as_view(), name='updateRegisteredKitchen'),
    re_path(r'^(?P<pk>\d+)/deleteKitchen$', deleteRegisteredKitchen.as_view(), name='deleteRegisteredKitchen'),
    path('signup/',views.signup,name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='userModule/user_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
    #url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    #url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

serviceProviderApp/models.py
from django.db import models
from django.urls import reverse
from userModule.models import User

# Create your models here.
class menuItem(models.Model):
    name=models.CharField(max_length=200,db_index=True,default='')
    veg=models.BooleanField(default=False)
    price=models.DecimalField(max_digits=10, decimal_places=2,db_index=True,default='')

    def __str__(self):
        return self.name

class Kitchen2Register(models.Model):
    #username=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    username = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=200, db_index=True)
    email=models.CharField(max_length=50)
    image = models.ImageField(upload_to='kitchens/',blank=True)
    description = models.TextField(blank=True)
    #menu=models.ForeignKey(menuItem,on_delete=models.CASCADE,blank=True,null=True)
    menu = models.ManyToManyField(menuItem)
    TIMES_TO_WORK = [
        ('Tm1','8:00'),
        ('Tm2','8:30'),
        ('Tm3','9:00'),
        ('Tm4','9:30'),
        ('Tm5','10:00'),
        ('Tm6', '10:30'),
        ('Tm7', '11:00'),
        ('Tm8', '11:30'),
        ('Tm9', '12:00'),
        ('Tm10', '12:30'),
        ('Tm11', '13:00'),
        ('Tm12', '13:30'),
        ('Tm13', '14:00'),
        ('Tm14', '14:30'),
        ('Tm15', '15:00'),
        ('Tm16', '15:30'),
        ('Tm17', '16:00'),
        ('Tm18', '16:30'),
        ('Tm19', '17:00'),
    ]
    monday = models.BooleanField(default=False)
    mondayStartTime = models.CharField(max_length=4,choices=TIMES_TO_WORK,default='Tm1',)
    mondayEndTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm19', )
    tuesday=models.BooleanField(default=False)
    tuesdayStartTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm1', )
    tuesdayEndTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm19', )
    wednesday = models.BooleanField(default=False)
    wednesdayStartTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm1', )
    wednesdayEndTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm19', )
    thursday = models.BooleanField(default=False)
    thursdayStartTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm1', )
    thursdayEndTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm19', )
    friday = models.BooleanField(default=False)
    fridayStartTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm1', )
    fridayEndTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm19', )
    saturday = models.BooleanField(default=False)
    saturdayStartTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm1', )
    saturdayEndTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm19', )
    sunday = models.BooleanField(default=False)
    sundayStartTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm1', )
    sundayEndTime = models.CharField(max_length=4, choices=TIMES_TO_WORK, default='Tm19', )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('userModule:kitchen_detail', args=[self.id])

serviceProviderApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userModule.models import User
from .models import Kitchen2Register

class ProviderRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    #QPGdP7RSSrazv6i
    class Meta:
        #model=Kitchen2Register
        #fields=('name','email')
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(ProviderRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_provider = True
        if commit:
            user.save()
        return user

serviceProviderApp/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import UpdateView,CreateView
from serviceProviderApp.models import Kitchen2Register
from django.http import HttpResponseRedirect,HttpResponse
from . import forms
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse
from cart.cart import Cart
from django.urls import reverse

# Create your views here.

def ProviderRegisterView(request):
    cart = Cart(request)
    if "return" in request.POST:
        return redirect('serviceProviderApp:kitchenCreate')
    elif request.method == "POST":
        form = forms.ProviderRegisterForm(request.POST)
        if form.is_valid():
            # user = form.save()
            # form.instance.username
            username = form.cleaned_data.get('username')
            messages.success(request, f'Registered Success for {username}')

            raw_password = form.clean_password2()
            #user = authenticate(username=username, password=raw_password)
            user=form.save()
            #login(request, user)
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('serviceProviderApp:kitchenCreate')
        else:
            return HttpResponse("Form Invalid!  Can not register kitchen!")
    else:
        form = forms.ProviderRegisterForm()
    return render(request, 'serviceProviderApp/providerSignUp.html', {'form': form,'cart':cart})

class KitchenUpdate(UpdateView):
    model=Kitchen2Register
    fields=['image','description','menu','monday','tuesday','wednesday','thursday','friday','saturday','sunday','mondayStartTime','mondayEndTime','tuesdayStartTime','tuesdayEndTime','wednesdayStartTime','wednesdayEndTime','thursdayStartTime','thursdayEndTime','fridayStartTime','fridayEndTime','saturdayStartTime','saturdayEndTime','sundayStartTime','sundayEndTime']
    template_name = 'serviceProviderApp/kitchenUpdate.html'

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            k = Kitchen2Register.objects.latest('id')
            Kitchen2Register.objects.filter(id=k.id).delete()
            url = '../create' #self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            k = Kitchen2Register.objects.latest('id')
            setattr(k, 'username', request.user)
            k.save()
            return super(KitchenUpdate, self).post(request, *args, **kwargs)
            #return HttpResponse("Success!")
            #k = Kitchen2Register.objects.all()  # filter(available=True)
            #cart = Cart(request)
            #return HttpResponseRedirect(reverse('userModule:kitchen_list',kwargs={'kitchens':k,'cart':cart}))
            #return HttpResponseRedirect(reverse('userModule:kitchen_list'))

    success_url = '../../user' #reverse('userModule:kitchen_list')

class registerKitchen(CreateView):
    model=Kitchen2Register
    fields=['username']
    template_name='serviceProviderApp/providerSignUp.html'

    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        if request.method == "POST":
            form = forms.ProviderRegisterForm(request.POST)
            if form.is_valid():
                # user = form.save()
                # form.instance.username
                username = form.cleaned_data.get('username')
                messages.success(request, f'Registered Success for {username}')

                raw_password = form.clean_password2()
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect('serviceProviderApp:kitchenUpdate')
            else:
                return HttpResponse("Form Invalid!  Can not register kitchen!")
        else:
            form = forms.ProviderRegisterForm()
        return render(request, 'serviceProviderApp/providerSignUp.html', {'form': form, 'cart': cart})

serviceProviderApp/templates/serviceProviderApp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}FEASTFREEDOM{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>

    <div id="header">
        <a href="/" class="logo"><u><span style="color:red">FEAST</span><span style="color:blue">FREEDOM</span></u><br><b>Feast</b> like a <b>Beast</b></a>
        <a href="{% url 'serviceProviderApp:providersignup' %}" class="serviceProvider">Provider Register Now | </a>
        {% if user.is_authenticated %}
            <a href="{% url 'userModule:logout' %}">Logout | </a>
            You Are Logged in as: {{ user.username }}
        {% else %}
            <a href="{% url 'userModule:login' %}">Login | </a>
            <a href="{% url 'userModule:signup' %}">Signup</a>
        {% endif %}
    </div>
    <div id="subheader">
        <div class="cart"></div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

serviceProviderApp/templates/serviceProviderApp/forms.html
{% for field in form %}
<p>
  {{ field.label_tag }}
  <br>
  {{ field }}
  <br>
  {% if field.help_text %}
  <br>
    <small style="color: grey"><br>{{ field.help_text }}</small>
  {% endif %}
  <br>
  {% for error in field.errors %}
    <p style="color: red" >{{ error }}</p>
  {% endfor %}
</p>
{% endfor %}

serviceProviderApp/templates/serviceProviderApp/kitchenCreate.html
{% extends 'serviceProviderApp/base.html' %}

{% block content %}
<h1>Register Your Kitchen</h1>
<br>
{% if user.is_authenticated %}
    <form method="post">{% csrf_token %}
        <b>User Name</b><br>
        {# {{ form.username }} #}
        {{ user }}
        <br>
        <br>
        <b>Kitchen Name</b><br>
        {{ form.name }}
        <br>
        <br>
        <b>Kitchen Email</b><br>
        {{ form.email }}
        <br>
        <br>
        <input type="submit" value="Save">
    </form>
{% else %}
    You must login with an account to register a kitchen.<br><br>
    Please select one of the following options:<br>
    <a href="{% url 'userModule:login' %}">Login | </a>
    <a href="{% url 'userModule:signup' %}">Signup</a>
{% endif %}
<form method="post">{% csrf_token %}
    <br>
    <input type="submit" name="cancel" value="Cancel">
</form>
{% endblock content %}

serviceProviderApp/templates/serviceProviderApp/kitchenDelete.html
<b>Delete Kitchen</b><br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Delete">
</form>

serviceProviderApp/templates/serviceProviderApp/kitchenEdit.html
{% extends 'serviceProviderApp/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {# {{ form.as_p }} #}
    <h1>Edit Your Kitchen's Details</h1>
    <br>
    <b>Kitchen Name</b><br>
    {{ form.name }}
    <br>
    <br>
    <b>Kitchen Email</b><br>
    {{ form.email }}
    <br>
    <br>
    <b>Kitchen Image</b><br>
    {{ form.image }}
    <br>
    <br>
    <b>Description of Kitchen</b><br>
    {{ form.description }}
    <br>
    <br>
    <b>Kitchen Menu</b><br>
    {% url 'serviceProviderApp:createMenuItem' as the_url %}
    {{ form.menu }} <a href="{{ the_url }}">Add Menu Item</a>
    <br>
    <br>
    <b>Hours of Operation</b><br><br>
    <b>&nbsp&nbsp&nbsp&nbsp&nbspDay&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspStart Time&nbsp&nbspEnd Time</b><br>
    <hr>
    Monday&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.monday }}&nbsp{{ form.mondayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.mondayEndTime }}<br>
    <hr>
    Tuesday&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.tuesday }} {{ form.tuesdayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.tuesdayEndTime }}<br>
    <hr>
    Wednesday{{ form.wednesday }} {{ form.wednesdayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.wednesdayEndTime }}<br>
    <hr>
    Thursday&nbsp&nbsp&nbsp{{ form.thursday }} {{ form.thursdayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.thursdayEndTime }}<br>
    <hr>
    Friday&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.friday }} {{ form.fridayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.fridayEndTime }}<br>
    <hr>
    Saturday&nbsp&nbsp&nbsp{{ form.saturday }} {{ form.saturdayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.saturdayEndTime }}<br>
    <hr>
    Sunday&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.sunday }} {{ form.sundayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.sundayEndTime }}<br>
    <hr>
    <input type="submit" name="cancel" value="Cancel"> <input type="submit" value="Save">
</form>
{% endblock content %}

serviceProviderApp/templates/serviceProviderApp/kitchenUpdate.html
{% extends 'serviceProviderApp/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {# {{ form.as_p }} #}
    <h1>Add Your Kitchen's Details</h1>
    <br>
    <b>Kitchen Image</b><br>
    {{ form.image }}
    <br>
    <br>
    <b>Description of Kitchen</b><br>
    {{ form.description }}
    <br>
    <br>
    <b>Kitchen Menu</b><br>
    {% url 'serviceProviderApp:createMenuItem' as the_url %}
    {{ form.menu }} <a href="{{ the_url }}">Add Menu Item</a>
    <br>
    <br>
    <b>Hours of Operation</b><br><br>
    <b>&nbsp&nbsp&nbsp&nbsp&nbspDay&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspStart Time&nbsp&nbspEnd Time</b><br>
    <hr>
    Monday&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.monday }}&nbsp{{ form.mondayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.mondayEndTime }}<br>
    <hr>
    Tuesday&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.tuesday }} {{ form.tuesdayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.tuesdayEndTime }}<br>
    <hr>
    Wednesday{{ form.wednesday }} {{ form.wednesdayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.wednesdayEndTime }}<br>
    <hr>
    Thursday&nbsp&nbsp&nbsp{{ form.thursday }} {{ form.thursdayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.thursdayEndTime }}<br>
    <hr>
    Friday&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.friday }} {{ form.fridayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.fridayEndTime }}<br>
    <hr>
    Saturday&nbsp&nbsp&nbsp{{ form.saturday }} {{ form.saturdayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.saturdayEndTime }}<br>
    <hr>
    Sunday&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.sunday }} {{ form.sundayStartTime }}&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ form.sundayEndTime }}<br>
    <hr>
    <input type="submit" name="cancel" value="Cancel"> <input type="submit" value="Save">
</form>
{% endblock content %}

serviceProviderApp/templates/serviceProviderApp/providerSignUp.html
{% extends 'serviceProviderApp/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <br>
    <input type="submit" name="return" value="Returning Kitchen Provider?">
    <input name="next" type="hidden" value="{% url 'serviceProviderApp:kitchenCreate' %}">
</form>

<form method="POST">
{% csrf_token %}
    <br>
    <b>Register a New Kitchen Provider</b><br>
{% include 'serviceProviderApp/forms.html' %}

<input type="submit" value='Next'>

</form>

{% endblock content %}