cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myProject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include(('myApp.urls','myApp'), namespace='myApp')),
    re_path(r'^provider/', include(('serviceProviderApp.urls','serviceProviderApp'), namespace='serviceProviderApp')),
    re_path(r'^user/', include(('userModule.urls','userModule'), namespace='userModule')),
    re_path(r'^cart/', include(('cart.urls','cart'), namespace='cart')),
    re_path(r'^orders/', include(('orders.urls','orders'), namespace='orders')),
    url(r'^payment/', include(('payment.urls','payment'), namespace='payment')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

userModule/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse
from userModule.views import updateMenuItem,deleteMenuItem,updateRegisteredKitchen,deleteRegisteredKitchen

urlpatterns = [
    re_path(r'^$', views.kitchen_list, name='kitchen_list'),
    re_path(r'^(?P<id>\d+)/$', views.kitchen_detail, name='kitchen_detail'),
    re_path(r'^(?P<pk>\d+)/editMenuItem$', updateMenuItem.as_view(), name='editMenuItem'),
    re_path(r'^(?P<pk>\d+)/deleteMenuItem$', deleteMenuItem.as_view(), name='deleteMenuItem'),
    re_path(r'^(?P<pk>\d+)/editKitchen$', updateRegisteredKitchen.as_view(), name='updateRegisteredKitchen'),
    re_path(r'^(?P<pk>\d+)/deleteKitchen$', deleteRegisteredKitchen.as_view(), name='deleteRegisteredKitchen'),
    path('signup/',views.signup,name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='userModule/user_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
    #url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    #url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

userModule/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_provider = models.BooleanField(default=False)
    question1 = models.CharField(blank=False, max_length=30)
    question2 = models.CharField(blank=False, max_length=30)
    answer1 = models.TextField(blank=False, max_length=30)
    answer2 = models.TextField(blank=False, max_length=30)

    def __str__(self):
        return self.username

userModule/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password
from .models import User

SECURITY_QUESTIONS = (
    ('0','What was the house number and street name you lived in as a child?'),
    ('1','What were the last four digits of your childhood telephone number?'),
    ('2','What primary school did you attend?'),
    ('3','In what town or city was your first full time job?'),
    ('4','In what town or city did you meet your spouse/partner?'),
    ('5','What is the middle name of your oldest child?'),
    ('6',"What are the last five digits of your driver's licence number?"),
    ('7',"What is your grandmother's (on your mother's side) maiden name?"),
    ('8',"What is your spouse or partner's mother's maiden name?"),
    ('9','In what town or city did your mother and father meet?'),
    ('10','What time of the day were you born? (hh:mm)'),
    ('11','What time of the day was your first child born? (hh:mm)'),
)

class RegularUserCreation(UserCreationForm):
    email = forms.EmailField(required=True)
    question1 = forms.ChoiceField(choices=SECURITY_QUESTIONS)
    question2 = forms.ChoiceField(choices=SECURITY_QUESTIONS)
    answer1 = forms.CharField(min_length=1, max_length=30)
    answer2 = forms.CharField(min_length=1, max_length=30)

    question1.widget.attrs.update({'style': 'font-size:12pt'})
    question2.widget.attrs.update({'style': 'font-size:12pt'})

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2",'question1','answer1','question2','answer2')

    def save(self, commit=True):
        user = super(RegularUserCreation, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.question1 = self.cleaned_data["question1"]
        user.question2 = self.cleaned_data["question2"]
        user.answer1 = make_password(self.cleaned_data["answer1"])
        user.answer2 = make_password(self.cleaned_data["answer2"])

        if commit:
            user.save()
        return user

userModule/views.py
from django.shortcuts import render,get_object_or_404, redirect
#from userModule.models import Kitchen
from django.urls import reverse
from serviceProviderApp.models import Kitchen2Register,menuItem
from cart.forms import CartAddProductForm
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from userModule.forms import RegularUserCreation
from cart.cart import Cart
from django.http import HttpResponseRedirect,HttpResponse
from userModule.get_username import get_username

# Create your views here.
def kitchen_list(request):
    #category = None
    #categories = Category.objects.all()
    k = Kitchen2Register.objects.all() #filter(available=True)
    cart = Cart(request)
    #if category_slug:
    #    category = get_object_or_404(Category, slug=category_slug)
    #    products = products.filter(category=category)
    #return render(request, 'userModule/kitchen_list.html', {'category': category,'categories': categories,'products': products})
    return render(request, 'userModule/kitchen_list.html',{'kitchens':k,'cart':cart})

def kitchen_detail(request, id):
    kitchen = get_object_or_404(Kitchen2Register, id=id)
    #for t in kitchen.menu.all():
    #    print(t.id)
    cart_product_form = CartAddProductForm()
    cart = Cart(request)
    if "cancel" in request.POST:
        url='..'
        return HttpResponseRedirect(url)
    else:
        #return render(request,'shop/product/detail.html',{'product': kitchen,'cart_product_form': cart_product_form})
        return render(request, 'userModule/kitchen_detail.html', {'kitchen': kitchen, 'cart_product_form': cart_product_form,'cart':cart})

#def createMenuItem(request,id):
#    k=Kitchen2Register.objects.get(id)
#    m=k.menu_set.create()

class createMenuItem(CreateView):
    model=menuItem
    fields=['name','veg','price']
    template_name = 'userModule/create_menuItem.html'

    def get_success_url(self):
        k=Kitchen2Register.objects.latest('id')
        return reverse('serviceProviderApp:kitchenUpdate', args=(k.id,))

    success_url = get_success_url

class updateMenuItem(UpdateView):
    model=menuItem
    fields=['name','veg','price']
    template_name = 'userModule/edit_menuItem.html'

    #def get_success_url(self):
    #    k=Kitchen2Register.objects.latest('id')
    #    return reverse('userModule:kitchen_detail', args=(k.id,))

    success_url = '..' #get_success_url

class deleteMenuItem(DeleteView):
    model=menuItem
    fields=['name','veg','price']
    template_name = 'userModule/delete_menuItem.html'

    #def get_success_url(self):
    #    k=Kitchen2Register.objects.latest('id')
    #    return reverse('userModule:kitchen_detail', args=(k.id,))

    success_url = '..' #get_success_url

class createKitchen(CreateView):
#class createKitchen(UpdateView):
    model=Kitchen2Register
    #fields=['name','email','image','description','menu','monday','tuesday','wednesday','thursday','friday','saturday','sunday','mondayStartTime','mondayEndTime','tuesdayStartTime','tuesdayEndTime','wednesdayStartTime','wednesdayEndTime','thursdayStartTime','thursdayEndTime','fridayStartTime','fridayEndTime','saturdayStartTime','saturdayEndTime','sundayStartTime','sundayEndTime']
    #fields=['username','name','email']
    fields=['name','email']
    template_name = 'serviceProviderApp/kitchenCreate.html'

    def get_success_url(self):
        #print(self.object.id)
        #k = Kitchen2Register.objects.latest('id')
        #setattr(self.object, 'username', request.user)
        #k.save()
        #req=get_username()
        #setattr(self, 'username', req.user)
        #self.save()
        #print(req.user)
        return reverse('serviceProviderApp:kitchenUpdate', args=(self.object.id,))

    def post(self, request, *args, **kwargs):
        #self.object=self.get_object(id=args)
        if "cancel" in request.POST:
            url = '..' #self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            #setattr(self.object, 'username', request.user)
            #self.object.save()
            return super(createKitchen, self).post(request, *args, **kwargs)
            #return HttpResponse("Success!")
            #url = self.get_success_url()#reverse('serviceProviderApp:kitchenUpdate', args=(self.object.id,))
            #return HttpResponseRedirect(url)

    #def save(self,*args,**kwargs):
    #    req = get_username()
    #    setattr(self, 'username', req.user)
    #    self.save()

    success_url = get_success_url

class updateRegisteredKitchen(UpdateView):
    model=Kitchen2Register
    fields=['name','email','image','description','menu','monday','tuesday','wednesday','thursday','friday','saturday','sunday','mondayStartTime','mondayEndTime','tuesdayStartTime','tuesdayEndTime','wednesdayStartTime','wednesdayEndTime','thursdayStartTime','thursdayEndTime','fridayStartTime','fridayEndTime','saturdayStartTime','saturdayEndTime','sundayStartTime','sundayEndTime']
    template_name = 'serviceProviderApp/kitchenEdit.html'

    def get_success_url(self):
        k=Kitchen2Register.objects.latest('id')
        return reverse('userModule:kitchen_detail', args=(k.id,))

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = '..' #self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(updateRegisteredKitchen, self).post(request, *args, **kwargs)

    success_url = get_success_url

class deleteRegisteredKitchen(DeleteView):
    model=Kitchen2Register
    fields=['name','email','image','description','menu','monday','tuesday','wednesday','thursday','friday','saturday','sunday','mondayStartTime','mondayEndTime','tuesdayStartTime','tuesdayEndTime','wednesdayStartTime','wednesdayEndTime','thursdayStartTime','thursdayEndTime','fridayStartTime','fridayEndTime','saturdayStartTime','saturdayEndTime','sundayStartTime','sundayEndTime']
    template_name = 'serviceProviderApp/kitchenDelete.html'

    success_url = '..'

@login_required
def logout(request):
    logout(request)
    return redirect('myApp:index')

def signup(request):
    if request.method == "POST":
        form = RegularUserCreation(request.POST)
        if form.is_valid():
            form.save()
            # form.instance.username
            username = form.cleaned_data.get('username')
            raw_password = form.clean_password2()
            user = authenticate(username=username,password=raw_password)
            login(request,user)
            #return redirect('myApp:index')
            return redirect('userModule:kitchen_list')
    else:
        form = RegularUserCreation()
    return render(request,'userModule/user_signup.html', {'form':form})

userModule/templates/userModule/create_menuItem.html
<b>Create a New Menu Item</b><br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>

userModule/templates/userModule/delete_menuItem.html
<b>Delete Menu Item</b><br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Delete">
</form>

userModule/templates/userModule/edit_menuItem.html
<b>Edit a Menu Item</b><br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

userModule/templates/userModule/forms.html
{% for field in form %}
<p>
    {% if field.label == 'Question1' or 'Question2' %}
        {{ field.label_tag }}
        {{ field }}
        <br>
    {% else %}
        {{ field.label_tag }}
        <br>
        {{ field }}
    {% endif %}
    <br>
  {% if field.help_text %}
  <br>
    <small style="color: grey"><br>{{ field.help_text }}</small>
  {% endif %}
  <br>
  {% for error in field.errors %}
    <p style="color: red" >{{ error }}</p>
    <br>
  {% endfor %}
</p>
{% endfor %}

userModule/templates/userModule/kitchen_detail.html
{% extends "myApp/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <br>
        <form method="post">{% csrf_token %}
            <input type="submit" name="cancel" value="Return to Kitchens">
            <input name="next" type="hidden" value="{% url 'userModule:kitchen_list' %}">
        </form>
        {% if user == kitchen.username %}
            {% url 'userModule:updateRegisteredKitchen' pk=kitchen.id as kit_edit_url %}
            {% url 'userModule:deleteRegisteredKitchen' pk=kitchen.id as kit_del_url %}
            <h1>{{ kitchen.name }} (<a href="{{ kit_edit_url }}" style="color:red">Edit</a>) (<a href="{{ kit_del_url }}" style="color:red">Delete</a>)</h1>
        {% else %}
            <h1>{{ kitchen.name }}</h1>
        {% endif %}
        {{ kitchen.description|linebreaks }}<br>
        <h1>Menu</h1><br>
        {# <img src="{% if kitchen.image %}{{ kitchen.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"> #}
        {% for m in kitchen.menu.all %}
            {% if user == kitchen.username %}
                {% url 'userModule:editMenuItem' pk=m.id as edit_url %}
                {% url 'userModule:deleteMenuItem' pk=m.id as del_url %}
                <a href="{{ edit_url }}" style="color:red">Edit</a> || <a href="{{ del_url }}" style="color:red">Delete</a><br>
            {% endif %}
            <b>{{ m.name }}</b> || <span style="color:blue">${{ m.price }}</span>
            {% if m.veg %}
                <b><span style="color: green"><br>Vegetarian</span></b><br>
            {% endif %}
            <form action="{% url "cart:cart_add" m.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Add to cart">
            </form>
            <br>
        {% endfor %}
    </div>
{% endblock %}

userModule/templates/userModule/kitchen_list.html
{% extends "myApp/base.html" %}
{% load static %}

{% block title %}
    Kitchens
{% endblock %}

{% block content %}
    <div id="main" class="product-list">
        <h1>Kitchens</h1>
        {% for k in kitchens %}
            <div class="item">
                <div class="img">
                    <a href="{{ k.get_absolute_url }}">
                        <img src="{% if k.image %}{{ k.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                    <a href="{{ k.get_absolute_url }}">{{ k.name }}</a><br>
                    {# ${{ k.price }} #}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

userModule/templates/userModule/user_login.html
{% extends 'myApp/base.html' %}

{% block content %}
<form method="POST">
{% csrf_token %}

{% include 'userModule/forms.html' %}

<input type="submit" value='Login'>
<input name="next" type="hidden" value="{% url 'userModule:kitchen_list' %}">
</form>

{% endblock content %}

userModule/templates/userModule/user_signup.html
{% extends 'myApp/base.html' %}

{% block content %}
<form method="POST">
{% csrf_token %}

{% include 'userModule/forms.html' %}

<input type="submit" value='Save'>
</form>

{% endblock content %}