cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myApp/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views
#from productApp.views import addProduct,buyProducts,deleteProduct

urlpatterns = [
	re_path(r'^$', views.index, name='index'),
	#url(r'^viewProducts/',views.viewProducts,name='viewProducts'),
	#url(r'^login/', auth_views.LoginView.as_view(template_name='productApp/login.html', success_url='viewProducts/'),name='login'),
	#url(r'^logout/', auth_views.LogoutView.as_view(template_name='productApp/logged_out.html'),name='logout'),
	#url(r'^buyProduct/(?P<pk>\d+)/',views.buyProducts,name='buyProduct'),
	#url(r'^buyProduct/(?P<pk>\d+)/',buyProducts.as_view(),name='buyProduct'),
    #url(r'^removeProduct/(?P<pk>\d+)/$',deleteProduct.as_view(),name='deleteProduct'),
	#url(r'^addProduct/$',addProduct.as_view(),name='addProduct')
]

myProject/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include(('myApp.urls','myApp'), namespace='myApp')),
    re_path(r'^provider/', include(('serviceProviderApp.urls','serviceProviderApp'), namespace='serviceProviderApp')),
    re_path(r'^user/', include(('userModule.urls','userModule'), namespace='userModule')),
    re_path(r'^cart/', include(('cart.urls','cart'), namespace='cart')),
    re_path(r'^orders/', include(('orders.urls','orders'), namespace='orders')),
    url(r'^payment/', include(('payment.urls','payment'), namespace='payment')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

serviceProviderApp/urls.py
from django.urls import path, re_path
from . import views
from serviceProviderApp.views import KitchenUpdate, ProviderRegisterView,registerKitchen
from userModule.views import createMenuItem,createKitchen
from django.conf.urls import url

urlpatterns = [
    re_path(r'^$',views.ProviderRegisterView, name='providersignup'),
    #re_path(r'^$',registerKitchen.as_view(), name='providersignup'),
    re_path(r'^create/$',createKitchen.as_view(),name='kitchenCreate'),
    re_path(r'^(?P<pk>\d+)$',KitchenUpdate.as_view(),name='kitchenUpdate'),
    #url(r'^(?P<pk>\d+)/createMenuItem$', createMenuItem.as_view(), name='createMenuItem'),
    url(r'^createMenuItem$', createMenuItem.as_view(), name='createMenuItem'),
    #url(r'^$', views.product_list, name='product_list'),
    #url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    #url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

userModule/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse
from userModule.views import updateMenuItem,deleteMenuItem,updateRegisteredKitchen,deleteRegisteredKitchen

urlpatterns = [
    re_path(r'^$', views.kitchen_list, name='kitchen_list'),
    re_path(r'^(?P<id>\d+)/$', views.kitchen_detail, name='kitchen_detail'),
    re_path(r'^(?P<pk>\d+)/editMenuItem$', updateMenuItem.as_view(), name='editMenuItem'),
    re_path(r'^(?P<pk>\d+)/deleteMenuItem$', deleteMenuItem.as_view(), name='deleteMenuItem'),
    re_path(r'^(?P<pk>\d+)/editKitchen$', updateRegisteredKitchen.as_view(), name='updateRegisteredKitchen'),
    re_path(r'^(?P<pk>\d+)/deleteKitchen$', deleteRegisteredKitchen.as_view(), name='deleteRegisteredKitchen'),
    path('signup/',views.signup,name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='userModule/user_login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
    #url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    #url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

myApp/models.py
from django.db import models

# Create your models here.

myApp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from cart.forms import CartAddProductForm
from cart.cart import Cart
from serviceProviderApp.models import Kitchen2Register

# Create your views here.

def index(request):
	#cart_product_form = CartAddProductForm()
	cart = Cart(request)
	if request.POST:
		k = Kitchen2Register.objects.all()  # filter(available=True)
		return render(request, 'userModule/kitchen_list.html', {'kitchens': k, 'cart': cart})
	else:
		# return render(request,'shop/product/detail.html',{'product': kitchen,'cart_product_form': cart_product_form})
		#return render(request, 'userModule/kitchen_detail.html',{'kitchen': kitchen, 'cart_product_form': cart_product_form})
		return render(request,'myApp/home.html', {'cart': cart})

myApp/templates/myApp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}FEASTFREEDOM{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>

    <div id="header">
        <a href="/" class="logo"><u><span style="color:red">FEAST</span><span style="color:blue">FREEDOM</span></u><br><b>Feast</b> like a <b>Beast</b></a>
        {% if user.is_authenticated %}
            <a href="{% url 'userModule:logout' %}">Logout | </a>
            You Are Logged in as: {{ user.username }}
        {% else %}
            <a href="{% url 'serviceProviderApp:providersignup' %}" class="serviceProvider">Provider Register Now | </a>
            <a href="{% url 'userModule:login' %}">Login | </a>
            <a href="{% url 'userModule:signup' %}">Signup</a>
        {% endif %}
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your cart:
                    <a href="{% url "cart:cart_detail" %}">
                        {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <p>{{ Home_Text }}</p>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

myApp/templates/myApp/home.html
{% extends 'myApp/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <h1>Welcome to <span style="color:red">FEAST</span><span style="color:blue">FREEDOM</span>!</h1>
    <input type="submit" value="View Kitchens">
    <input name="next" type="hidden" value="{% url 'userModule:kitchen_list' %}">
</form>
{% endblock content %}